networks:
    alxarafe_network:
        name: alxarafe_network

services:
    alxarafe_nginx:
        image: nginx:alpine
        container_name: alxarafe_nginx
        restart: always
        env_file: ".env"
        ports:
            - "${HTTP_PORT}:80"
        networks:
            - alxarafe_network
        volumes:
            - ".:/var/www/html:rw"
            - "./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
        depends_on:
            - alxarafe_php
            - alxarafe_db

    alxarafe_php:
        container_name: alxarafe_php
        restart: always
        env_file: ".env"
        build:
            context: .
            dockerfile: .docker/php/Dockerfile
            args:
                - USER_ID=${USER_ID}
                - GROUP_ID=${GROUP_ID}
        networks:
            - alxarafe_network
        volumes:
            - ".:/var/www/html:rw"
        extra_hosts:
            - "host.docker.internal:host-gateway"

    alxarafe_db:
        image: mariadb:10.11
        container_name: alxarafe_db
        restart: always
        env_file: ".env"
        ports:
            - "${MARIADB_PORT}:3306"
        environment:
            - MARIADB_DATABASE=${MARIADB_DATABASE}
            - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
        networks:
            - alxarafe_network
        volumes:
            - "alxarafe_db_data:/var/lib/mysql"

    alxarafe_node:
        image: node:20-slim
        container_name: alxarafe_node
        user: "${USER_ID}:${GROUP_ID}"
        working_dir: /var/www/html
        env_file: ".env"
        volumes:
            - ".:/var/www/html:rw"
        # command: sh -c "npm install && npm run watch"
        networks:
            - alxarafe_network
        tty: true # Esto mantiene el contenedor vivo
        command: sh -c "npm install && npm run watch || tail -f /dev/null" # Fuerza a que no se apague

volumes:
    alxarafe_db_data: